### ISSUE TITLE
Не можна відкрити сторінку депутата

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#1]
https://lviv.rada4you.org/people/%D0%92%D0%B0%D0%BD%D1%8C_%D0%86%D0%B3%D0%BE%D1%80_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87

**Comment by beastie87** [comment]
Ой, я перепутав змінні в рахуванні(
І ще хочу зазначити у мене вийшло так що якщо депутат не прийшов на засідання тобто він відсутній,  то  депутат який тоже не був на засіданні є його другом, якщо треба зробити щоб тільки по відвідуваних голосуваннях, то скажіть я зміню алгорити

**Comment by beastie87** [comment]
done
