### ISSUE TITLE
поправити місяці в статистиці на сторінці депутата

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#10]
треба поправити січень, березень і червень
ось [тут](http://139.162.151.85:3001/people/%D0%90%D0%B4%D0%B0%D0%BC%D0%B8%D0%BA_%D0%9F%D0%B5%D1%82%D1%80%D0%BE_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87?month=2017-03)
----
![image](https://user-images.githubusercontent.com/14181306/28535481-3c37f62a-70ad-11e7-94cb-108d9b810e42.png)

**Comment by beastie87** [comment]
Done d95bd95
