### ISSUE TITLE
після 26.07 - - - - - -Забрати Садового і Забарила з фракцій, позафракційними

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#12]
реально?

**Comment by beastie87** [comment]
базу звичайно можемо змінити)

**Comment by beastie87** [comment]
Fix done!
https://lviv.rada4you.org/people?filter=%D0%9F%D0%BE%D0%B7%D0%B0%D1%84%D1%80%D0%B0%D0%BA%D1%86%D1%96%D0%B9%D0%BD%D0%B8%D0%B9&amp;sort=faction
