### ISSUE TITLE
рік обрання 2015

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#13]
депутатів обрали в 2015 році. 
[приклад](https://lviv.rada4you.org/people/%D0%94%D0%BE%D0%B2%D0%B6%D0%B8%D0%BA_%D0%92%D1%96%D0%BA%D1%82%D0%BE%D1%80%D1%96%D1%8F_%D0%92%D1%96%D0%BA%D1%82%D0%BE%D1%80%D1%96%D0%B2%D0%BD%D0%B0)

![image](https://user-images.githubusercontent.com/14181306/28570031-f06d1c8c-7144-11e7-85fa-590de14ff8ce.png)

**Comment by beastie87** [comment]
може це речення взагалі видалити?

2017-07-25 14:24 GMT+03:00 lisoffsky <notifications@github.com>:

**Comment by lisoffsky** [comment]
++

**Comment by beastie87** [comment]
Done!
