### ISSUE TITLE
фікс присутності.  зараз не зрозуміло зовсім. 

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#14]
на головній
![image](https://user-images.githubusercontent.com/14181306/28570358-85db4892-7146-11e7-94d2-37eeb6fe8180.png)

в профілі

![image](https://user-images.githubusercontent.com/14181306/28570344-747a91b6-7146-11e7-8672-f1561a9032e8.png)

**Comment by beastie87** [comment]
e7421df fix done
