### ISSUE TITLE
сумісне голосування за січень 2017 працює тільки для 3 фракцій

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#17]
[наприклад](https://lviv.rada4you.org/sumisne-holosuvannia?month=2017-01&party=%D0%A3%D0%9A%D0%A0%D0%9E%D0%9F&utf8=%E2%9C%93), для УКРОПА не працює

![image](https://user-images.githubusercontent.com/14181306/28576461-90991f8c-715c-11e7-918e-a8077502d69b.png)

**Comment by beastie87** [comment]
хм https://lviv.rada4you.org/sumisne-holosuvannia/api?month=2017-01

**Comment by beastie87** [comment]
0 голосувань за підтримку, тому й не було графіку
Fix Done!
