### ISSUE TITLE
голосування з відвідуваністю = 0

### ISSUE THREAD

**Issue by GS-0001** [OPORA/publicwhip-lviv#18]
станом на 31 липня в системі є одне голосування з відвідуваністю = 0

https://lviv.rada4you.org/divisions?filter_min=0&amp;filter_max=0&amp;sort=attendance

1. https://lviv.rada4you.org/divisions/2015-09-30/2

варто перевірити ситуацію "чому"?

**Comment by beastie87** [comment]
http://lvivvoted.oporaua.org/votes_events/2015-10-01 ось це голосування в базі голосувань, 
я думаю що це голосування відпувалось в попередній раді до виборів, ось посилання на файл результату голосування https://www.lvivrada.gov.ua/images/%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA%20%D0%B4%D0%B5%D0%BD%D0%BD%D0%B8%D0%B9/30.09/rez/1.rtf і звісно ж Алексєєв Олександр Олександрович не є депутатом типерішньої ради. Для вирішення даної ситуації придлагаю видалити данне голосування

**Comment by lisoffsky** [comment]
так, це попереднє скликання. Нові ради по факту почали працювати з листопада 2015 року

**Comment by lisoffsky** [comment]
@beastie87  давай видалимо, це не наше скликання :)

**Comment by beastie87** [comment]
Drop was done)
