### ISSUE TITLE
У "Член фракції політичної партії "Свобода" обрано по окрогу номер 63" змінити 

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#3]
слово "окрогу" на "округу"
прикл [тут](https://lviv.rada4you.org/people/%D0%91%D0%B0%D1%82%D1%8E%D0%BA_%D0%9C%D0%B0%D1%80%E2%80%99%D1%8F%D0%BD%D0%B0_%D0%92%D0%BE%D0%BB%D0%BE%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D1%96%D0%B2%D0%BD%D0%B0)
![image](https://cloud.githubusercontent.com/assets/14181306/25660261/1c8e6b80-3014-11e7-93aa-de75afbb6f6e.png)

**Comment by beastie87** [comment]
done
