### ISSUE TITLE
Друзі по голосуваннях не клікабельні

### ISSUE THREAD

**Issue by lisoffsky** [OPORA/publicwhip-lviv#8]
ось [тут](http://139.162.151.85:3001/people/detal/%D0%A1%D0%B0%D0%B4%D0%BE%D0%B2%D0%B8%D0%B9_%D0%90%D0%BD%D0%B4%D1%80%D1%96%D0%B9_%D0%86%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%87?month=full&vote=friends) наприклад

![image](https://user-images.githubusercontent.com/14181306/28532639-12061e54-70a3-11e7-99ed-97a79a36e203.png)

і офтоп, але скажи, issue #6 враховано ж?

**Comment by beastie87** [comment]
Done
